on:
  push:
    branches : [ "main" ]
jobs:
  glitch-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/metalandcoffee/in-the-queue-app.git"
        SOURCE_BRANCH: "main"
        DESTINATION_REPO: ${{ secrets.GLITCH_GIT_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
